ProFive/AppFive/urls.py
from django.urls import path
from . import views

app_name = 'appfive'

urlpatterns = [
    path('home/',views.index,name='home'),
    path('other/',views.other, name='other'),
    path('register/',views.registeration,name = 'register'),
    path('user_login/',views.user_login, name = 'user_login'),
]

ProFive/ProFive/urls.py
from django.contrib import admin
from django.urls import path,include
from AppFive import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="homepage"),
    path('appfive/',include("AppFive.urls",namespace="appFive")),
    path('logout/',views.user_logout,name="logout"),
    path('special',views.special,name="special"),
]

ProFive/AppFive/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileinfo(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)

    # first_name = models.CharField(max_length=40)
    # last_name = models.CharField(max_length=40)
    # today_date = models.DateField(auto_now=True, auto_now_add=False)
    # User_age = models.DecimalField(max_digits=4, decimal_places=0)
    # User_email = models.EmailField(max_length=245)

# ADDITIONAL 
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to = 'Profile Pictures' , blank=True)

    def __str__(self): 
        return self.user.username

ProFive/AppFive/forms.py
from django import forms
from AppFive.models import UserProfileinfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User  
        fields = ('username','email','password')

class UserProfileinfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileinfo
        fields = ('portfolio_site','profile_pic')
        

ProFive/AppFive/views.py
from django.shortcuts import render
from AppFive.forms import UserForm, UserProfileinfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

# Create your views here

def index(request):
    content = {
        "A" : "[APPLE, BANANA, FRUITS]",
        "C" : "[CITA, CITRUS, CAT]"
    }
    return render(request,"AppFive/index.html")

def other(request):
    return render(request,"AppFive/other.html")


@login_required
def special(request):
    return HttpResponse("You are logged in!!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('appFive:home'))

def registeration(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileinfoForm(data = request.POST)

        if user_form.is_valid()and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileinfoForm()

    return render(request,"AppFive/registeration.html",{'user_form':user_form,
                                                       'profile_form':profile_form,
                                                       'registered' :registered})

def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active():
                login(request, user)
                # IF the user has logged in successfuly and he will be redirect back to homepage
                return HttpResponseRedirect(reverse('AppFive/index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else :
            print("InValid User tried to log in")
            print(f"Username:{username} and Password:{password}")
            print("Username:{} and Password:{}".format(username,password))
            return HttpResponse("INVALID EMAIL DETAILS SUBMITTED")
    
    else:
        return render(request, 'AppFive/login.html')

ProFive/templates/AppFive/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>appFive</title>
        {% load static %}
        <link href="{% static 'CSS/styles.css' %}" type="text/css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header
                class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
                <a class="navbar-brand brandname" href="/" target="_blank" rel="noopener noreferrer" title="Image">
                    BRAND
                </a>
        
                <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'appfive:home' %}" class="nav-link px-2 link-secondary">Home</a></li>
                    <li><a href="{% url 'appfive:other' %}" class="nav-link px-2 link-dark">Other</a></li>
                    <li><a href="{% url 'appfive:register' %}" class="nav-link px-2 link-dark">Register</a></li>
                    <li><a href="{% url 'admin:index' %}" class="nav-link px-2 link-dark">Admin</a></li>
                    <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
                </ul>
                


                <div class="col-md-3 text-end">
                    {% if not user.is_authenticated %}
                        <a href="{% url 'appfive:user_login' %}" name="login" class="nav-link px-2">
                        <button type="button" class="btn btn-outline-primary me-2">Login</button>
                        </a>
                    {% else %}
                        <a href="{% url 'logout' %}">
                        <button type="button" class="btn btn-primary">LOGOUT</button>
                        </a>
                    {% endif %}
                </div>    
            </header>
        </div>
        {% block body_block %}

        {% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="" type="javascript/text"></script>
    </body>
</html>

ProFive/templates/AppFive/index.html
<!DOCTYPE html>

 {% extends "AppFive/base.html" %}

    {% block body_block %}
    <div class="contianer-fluid">
        <h2>Namaste World</h2>
        <p>This is the APPFIVE Index File</p>
    </div>

    {% endblock %}

ProFive/templates/AppFive/login.html
<!DOCTYPE html>
<html lang="en" lang="en">
    <head>
        <meta charset="utf-8"/> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        {% load static %}
        <link rel="stylesheet" href="{% static 'CSS/login_styles.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous>
        <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
        </script>
        <link rel="stylesheet" href="https://kit.fontawesome.com/a3989a4830.css" crossorigin="anonymous">
        <title>Login Form</title>
    </head>

    <body>
        <div class="container" id="container">
            <div class="form-container log-in-container">
                <form action="{% url 'appfive:user_login' %}" method="POST">
                    {% csrf_token %}
                    <h1>Login</h1>
                    <div class="social-container">
                        <a href="https://www.facebook.com/" title="facebook" class="social"><i class="fa-brands fa-facebook"></a>
                        <a href="https://twitter.com/i/flow/login?input_flow_data=%7B%22requested_variant%22%3A%22eyJsYW5nIjoiZW4ifQ%3D%3D%22%7D" title="twitter" class="social"><i class="fa-brands fa-twitter"></i></a>
                    </div>
                    <span>or use your account</span>
                    <input name = "username" type="email" placeholder="Username/Email" />
                    <input name="password" type="password" placeholder="Password" />
                    <a href="#">Forgot your password?</a>
                    <button type="submit" id="log_btn" class="btn btn-outline-success">Log In</button>
                </form>
            </div>
            <div class="overlay-container">
                <div class="overlay">
                    <div class="overlay-panel overlay-right">
                        <h1>Login Here</h1>
                        <p>Django Project Five Login Page
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </body>

</html>

ProFive/templates/AppFive/other.html
<!DOCTYPE html>

    {% extends "AppFive/base.html" %}

    {% block body_block %}
    <div class="contianer-fluid">
        <h2>HELLO World</h2>
        <p>This is the APPFIVE OTHERFile</p>
    </div>

    {% endblock %}

ProFive/templates/AppFive/registeration.html
{% extends 'AppFive/base.html' %}
{% load static %}

{% block body_block %}

<div class = "container-fluid jumbotron">
    {% if registered %}
        <h2>Thank you for registering!</h2>
    {% else %}
        <h2>Register here!!</h2>
        <h3>Fill out of the form:</h3>
 
        <form enctype = "multipart/form-data" method = "POST">
            {% csrf_token %}
            <div>{{user_form.as_p}}</div>
            <div>{{ profile_form.as_p}}</div>
            <input type="submit" value="Register"> 
        </form>
 
        {% endif %}
{% endblock %}